# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

stages:
- stage: Build the app
  pool:
    vmImage: ubuntu-20.04

  jobs:
  - job: A1
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

- stage: Run some tests on the app
  jobs:
  - job: B1
    steps:
      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        displayName: 'pytest'
