# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Build
    jobs:
    - job: A1
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: Build the app
      strategy:
        matrix:
          Python36:
            python.version: '3.6'
          Python37:
            python.version: '3.7'

  - stage: Test
    jobs:
    - job: B1
      steps:
      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        displayName: Test the app
        condition: 

